services:
  wol:
    image: ghcr.io/creeper2556/wake-on-lan:latest
    container_name: wake-on-lan
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3579
